name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  squirrel:
    name: Squirrel
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          cache: true

      - name: Test
        run: |
          go test ./...
