name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  squirrel:
    name: Squirrel
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: squirrel
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: squirrel
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          cache: true

      - name: Test
        run: |
          go test

      - name: Integration (sqlite3)
        run: |
          CGO_ENABLED=1 go test -args -driver sqlite3
        working-directory: integration

      - name: Integration (mysql)
        run: |
          go test -args -driver mysql -dataSource root:root@/squirrel
        working-directory: integration

      - name: Integration (postgres)
        run: |
          go test -args -driver postgres -dataSource 'postgres://postgres:postgres@127.0.0.1/squirrel?sslmode=disable'
        working-directory: integration
